@urlBase = https://parseapi.back4app.com
@urlObjects = /functions

@XParseParseApplicationId = x4uHx8hJECtAPiKo4Z2f8IK9OUKRtcuUBBaUBHM9
@XParseRESTAPIKey = frnySy1R0hur1GkJPIrxoN6ucSZxuH3wdQzyUMEO

@id = 7SQxjSuRHE
###
# hello
POST {{urlBase}}{{urlObjects}}/hello
X-Parse-Application-Id: {{XParseParseApplicationId}}
X-Parse-REST-API-Key: {{XParseRESTAPIKey}}
Content-Type: application/json

{}
###
